function Plot_ExpData_Tensor_v10(Exp_Data_Tensor,individual_plots, plasmid_plots,promoter_plots,rbs_plots,varargin)
% Plot_ExpData_Tensor_v10
%
% Improved plotting function for experimental library data generated by
% Make_DataExp_Tensor_v1.m.
%
% Main changes relative to v1:
%   - publication-size figure windows, suitable for full-page landscape SI;
%   - larger fonts, thicker lines and larger markers;
%   - automatic export to PNG and SVG;
%   - optional short EC labels for supplementary figures;
%   - compact main-text variant of the ordered synthesis/burden figure;
%   - fixes sorting of mu error bars and point colors in Fano/CV panels.
%
% Backward compatible call:
%   Plot_ExpData_Tensor_v10(Data_Exp_Tensor_lib35,0,0,0)
%
% Recommended call:
%   Plot_ExpData_Tensor_v10(Data_Exp_Tensor_lib35,0,0,0,0, ...
%       'OutputDir', fullfile(SCRIPT_DIR,'Figures'), ...
%       'LabelMode','ec_code', ...        % 'ec_code' or 'bioparts'
%       'SaveFigures',true, ...
%       'MakeMainVariant',true);
%
% Notes:
%   For the Supplementary Information, short EC labels are recommended.
%   The mapping to full biopart composition is already provided in Table S1.
%
% How to tune font sizes:
%   - Main global controls are the optional name-value arguments
%       'SupplementFontSize' and 'MainFontSize'.
%     Example:
%       Plot_ExpData_Tensor_v10(Data_Exp_Tensor_lib35,0,0,0,0, ...
%           'SupplementFontSize',16,'MainFontSize',14);
%   - Axis-label sizes are set inside plot_ordered_pi_mu,
%     plot_ordered_bar, and the tiled Pi-vs-mu section by adding
%     small offsets to these base sizes.
%   - Tile tick-label density is controlled in force_mu_ticks(), called
%     inside the tiled Pi-vs-mu figure after xlim is set.
%   - For the tiled Pi-vs-mu supplementary figure, x tick labels are
%     forced to be slanted in every tile and the final tick is fixed at
%     the EC-specific maximum plotted mu value, with a small right margin
%     to prevent clipping during PNG/SVG export.
%   - In the tiled figure, both x and y axes are forced to three readable
%     ticks (minimum, middle and maximum/nice rounded values) to keep the
%     35-panel layout legible after export.

if nargin < 2 || isempty(individual_plots), individual_plots = 0; end
if nargin < 3 || isempty(plasmid_plots),    plasmid_plots    = 0; end %#ok<NASGU>
if nargin < 4 || isempty(promoter_plots),   promoter_plots   = 0; end %#ok<NASGU>
if nargin < 5 || isempty(rbs_plots),        rbs_plots        = 0; end %#ok<NASGU>

p = inputParser;
p.addParameter('OutputDir', fullfile(pwd,'Figures'), @(x)ischar(x)||isstring(x));
p.addParameter('SaveFigures', true, @(x)islogical(x)||isnumeric(x));
p.addParameter('MakeMainVariant', true, @(x)islogical(x)||isnumeric(x));
p.addParameter('LabelMode', 'ec_code', @(x)any(strcmpi(string(x),{'ec_code','bioparts','none'})));
p.addParameter('UseVerticalLabels', true, @(x)islogical(x)||isnumeric(x));
p.addParameter('SupplementFontSize', 14, @(x)isnumeric(x)&&isscalar(x));
p.addParameter('MainFontSize', 12, @(x)isnumeric(x)&&isscalar(x));
p.addParameter('FigurePrefix', 'Lib35_Experimental', @(x)ischar(x)||isstring(x));
p.addParameter('SaveTable', true, @(x)islogical(x)||isnumeric(x));
p.parse(varargin{:});
opt = p.Results;
opt.OutputDir = char(opt.OutputDir);
opt.FigurePrefix = char(opt.FigurePrefix);
if opt.SaveFigures && ~exist(opt.OutputDir,'dir')
    mkdir(opt.OutputDir);
end

% -------------------------------------------------------------------------
% Style constants
% -------------------------------------------------------------------------
color_blue = hex2rgb_local('#00008B');
color_grey = hex2rgb_local('#BFBFBF');
color_grey_dark = hex2rgb_local('#4B4B4B');
bar_edge = hex2rgb_local('#666666');

font_s = opt.SupplementFontSize;
font_m = opt.MainFontSize;

% -------------------------------------------------------------------------
% Collect data from tensor
% -------------------------------------------------------------------------
num_plasmids  = size(Exp_Data_Tensor,1);
num_promoters = size(Exp_Data_Tensor,2);
num_rbss      = size(Exp_Data_Tensor,3);

entries = struct('i',{},'j',{},'k',{},'bioparts',{},'label',{},'color',{}, ...
                 'Pi',{},'Pi_std',{},'Mu',{},'Mu_std',{},'Phi',{},'Phi_std',{});
q = 1;
for i = 1:num_plasmids
    for j = 1:num_promoters
        for k = 1:num_rbss
            if ~isempty(Exp_Data_Tensor{i,j,k})
                E = Exp_Data_Tensor{i,j,k};
                entries(q).i = i;
                entries(q).j = j;
                entries(q).k = k;
                entries(q).bioparts = char(string(E.TU_Bioparts));
                entries(q).label = make_ec_label(E, i, j, k, q, opt.LabelMode);
                entries(q).Pi = E.Data.Global_stats_Mumax_Pi_p(1,2);
                entries(q).Pi_std = E.Data.Global_stats_Mumax_Pi_p(2,2);
                entries(q).Mu = E.Data.Global_stats_Mumax_Pi_p(1,1);
                entries(q).Mu_std = E.Data.Global_stats_Mumax_Pi_p(2,1);
                entries(q).Phi = E.Data.Global_stats_Mumax_Phi_h(1,2);
                entries(q).Phi_std = E.Data.Global_stats_Mumax_Phi_h(2,2);
                if isfield(E,'TU_color_code') && ~isempty(E.TU_color_code)
                    entries(q).color = E.TU_color_code;
                else
                    entries(q).color = [0.7 0.7 0.7];
                end
                q = q + 1;
            end
        end
    end
end

nEC = numel(entries);
labels = {entries.label};
biopart_labels = {entries.bioparts};
Y_Pi = [entries.Pi];
Sigma_Y_Pi = [entries.Pi_std];
Y_Mu = [entries.Mu];
Sigma_Y_Mu = [entries.Mu_std];
Y_Phih = [entries.Phi];
Sigma_Y_Phih = [entries.Phi_std];
Color = reshape([entries.color],3,[])';

[~,Isorted] = sort(Y_Pi,'ascend');
labels_sorted = labels(Isorted);
biopart_labels_sorted = biopart_labels(Isorted);
Xsorted = categorical(labels_sorted);
Xsorted = reordercats(Xsorted, labels_sorted);

FanoFactor = Sigma_Y_Pi.^2 ./ Y_Pi;
CoefVar    = Sigma_Y_Pi ./ Y_Pi;

% Save table-like data for later use
if opt.SaveTable
    save(fullfile(opt.OutputDir,'Table_Lib_ExpData_Tensor_v10.mat'), ...
        'labels','labels_sorted','biopart_labels','biopart_labels_sorted', ...
        'Y_Pi','Sigma_Y_Pi','Y_Mu','Sigma_Y_Mu','Y_Phih','Sigma_Y_Phih', ...
        'FanoFactor','CoefVar','Isorted','Color','-mat');
end

% -------------------------------------------------------------------------
% FIGURE 1: ordered Pi(mu_m) + mu_m
% -------------------------------------------------------------------------
fig1 = figure('Name','Ordered synthesis rate and growth rate','Color','w', ...
    'Units','centimeters','Position',[1 1 72 28]);
tiledlayout(1,1,'Padding','compact','TileSpacing','compact');
ax1 = nexttile;
plot_ordered_pi_mu(ax1, Xsorted, Y_Pi(Isorted), Sigma_Y_Pi(Isorted), ...
    Y_Mu(Isorted), Sigma_Y_Mu(Isorted), Color(Isorted,:), color_blue, bar_edge, font_s, true);
if opt.UseVerticalLabels
    ax1.XTickLabelRotation = 90;
end
save_figure_if_requested(fig1,opt.OutputDir,[opt.FigurePrefix '_S2_ordered_Pi_mu'],opt.SaveFigures);

% -------------------------------------------------------------------------
% FIGURE 2: ordered Pi(mu_m) + Phi_h(mu_m), supplementary version
% -------------------------------------------------------------------------
fig2 = figure('Name','Ordered synthesis rate and cell burden','Color','w', ...
    'Units','centimeters','Position',[1 1 72 36]);
tl = tiledlayout(2,1,'Padding','compact','TileSpacing','compact');

ax21 = nexttile;
plot_ordered_pi_mu(ax21, Xsorted, Y_Pi(Isorted), Sigma_Y_Pi(Isorted), ...
    Y_Mu(Isorted), Sigma_Y_Mu(Isorted), Color(Isorted,:), color_blue, bar_edge, font_s, false);
ax21.XTickLabel = [];

ax22 = nexttile;
plot_ordered_bar(ax22, Xsorted, Y_Phih(Isorted), Sigma_Y_Phih(Isorted), ...
    Color(Isorted,:), color_blue, bar_edge, font_s, '$\hat{\Phi}_\mathrm{h}(\mu_\mathrm{m})\; (\%)$', true);
if opt.UseVerticalLabels
    ax22.XTickLabelRotation = 90;
end
xlabel(ax22,'Expression construct','FontSize',font_s,'Interpreter','none');
save_figure_if_requested(fig2,opt.OutputDir,[opt.FigurePrefix '_S2_ordered_Pi_burden_supplement'],opt.SaveFigures);

% -------------------------------------------------------------------------
% FIGURE 2 main-text compact variant: no EC names, only ordered EC index
% -------------------------------------------------------------------------
if opt.MakeMainVariant
    fig2m = figure('Name','Main compact ordered synthesis and burden','Color','w', ...
        'Units','centimeters','Position',[1 1 42 16]);
    tlm = tiledlayout(2,1,'Padding','compact','TileSpacing','compact');
    xnum = 1:nEC;
    axm1 = nexttile;
    plot_ordered_pi_mu_numeric(axm1, xnum, Y_Pi(Isorted), Sigma_Y_Pi(Isorted), ...
        Y_Mu(Isorted), Sigma_Y_Mu(Isorted), Color(Isorted,:), color_blue, bar_edge, font_m, false);
    axm1.XTickLabel = [];

    axm2 = nexttile;
    plot_ordered_bar_numeric(axm2, xnum, Y_Phih(Isorted), Sigma_Y_Phih(Isorted), ...
        Color(Isorted,:), color_blue, bar_edge, font_m, '$\hat{\Phi}_\mathrm{h}(\mu_\mathrm{m})\; (\%)$', true);
    axm2.XTick = [];
    axm2.XTickLabel = {};
    save_figure_if_requested(fig2m,opt.OutputDir,[opt.FigurePrefix '_Main_ordered_Pi_burden_compact'],opt.SaveFigures);
end

% -------------------------------------------------------------------------
% FIGURE 2 main-text compact variant
% -------------------------------------------------------------------------
if opt.MakeMainVariant
    fig2m = figure('Name','Main compact ordered synthesis and burden', ...
        'Color','w', ...
        'Units','centimeters', ...
        'Position',[1 1 42 19]);

    tlm = tiledlayout(2,1, ...
        'Padding','compact', ...
        'TileSpacing','compact');

    xnum = 1:nEC;

    axm1 = nexttile;
    plot_ordered_pi_mu_numeric(axm1, xnum, ...
        Y_Pi(Isorted), Sigma_Y_Pi(Isorted), ...
        Y_Mu(Isorted), Sigma_Y_Mu(Isorted), ...
        Color(Isorted,:), color_blue, bar_edge, 1.25*font_m, false);

    axm1.XTick = [];
    axm1.XTickLabel = {};

    axm2 = nexttile;
    plot_ordered_bar_numeric(axm2, xnum, ...
        Y_Phih(Isorted), Sigma_Y_Phih(Isorted), ...
        Color(Isorted,:), color_blue, bar_edge, 1.25*font_m, ...
        '$\hat{\Phi}_\mathrm{h}(\mu_\mathrm{m})\;(\%)$', true);

    % Restore ordered expression-construct labels on the lower panel.
    axm2.XTick = xnum;
    axm2.XTickLabel = labels_sorted;
    axm2.XTickLabelRotation = 90;
    axm2.TickLabelInterpreter = 'none';

    xlabel(axm2,'Expression construct', ...
        'FontName','Arial', ...
        'FontSize',1.6*font_m, ...
        'Interpreter','none');

    save_figure_if_requested(fig2m,opt.OutputDir, ...
        [opt.FigurePrefix '_Main_ordered_Pi_burden_compact'], ...
        opt.SaveFigures);
end

% -------------------------------------------------------------------------
% FIGURE 3: Pi(mu_m), Fano Factor, CV
% -------------------------------------------------------------------------
fig3 = figure('Name','Ordered synthesis variability summary','Color','w', ...
    'Units','centimeters','Position',[1 1 72 42]);
tl3 = tiledlayout(3,1,'Padding','compact','TileSpacing','compact');

ax31 = nexttile;
plot_ordered_bar(ax31, Xsorted, Y_Pi(Isorted), Sigma_Y_Pi(Isorted), ...
    Color(Isorted,:), color_blue, bar_edge, font_s, '$\Pi_\mathrm{p}(\mu_\mathrm{m})$', true);
ax31.XTickLabel = [];

ax32 = nexttile;
scatter(Xsorted, FanoFactor(Isorted), 80, Color(Isorted,:), 'filled', ...
    'MarkerEdgeColor', color_grey_dark, 'LineWidth', 0.5);
set_axis_common(ax32,font_s);
ylabel(ax32,'$\mathrm{FF}\left(\Pi_\mathrm{p}(\mu_\mathrm{m})\right)$','Interpreter','latex','FontSize',font_s+3);
set(ax32,'YScale','log');
ax32.XTickLabel = [];
grid(ax32,'on');

ax33 = nexttile;
scatter(Xsorted, CoefVar(Isorted), 80, Color(Isorted,:), 'filled', ...
    'MarkerEdgeColor', color_grey_dark, 'LineWidth', 0.5);
set_axis_common(ax33,font_s);
ylabel(ax33,'$\mathrm{CV}\left(\Pi_\mathrm{p}(\mu_\mathrm{m})\right)$','Interpreter','latex','FontSize',font_s+3);
if opt.UseVerticalLabels
    ax33.XTickLabelRotation = 90;
end
grid(ax33,'on');
xlabel(ax33,'Expression construct','FontSize',font_s,'Interpreter','none');
save_figure_if_requested(fig3,opt.OutputDir,[opt.FigurePrefix '_S2_variability_FF_CV'],opt.SaveFigures);

% -------------------------------------------------------------------------
% FIGURE 4: tiled Pi versus mu trajectories
% -------------------------------------------------------------------------
fig4 = figure('Name','Pi versus mu trajectories across ECs','Color','w', ...
    'Units','centimeters','Position',[1 1 92 34]);
tl4 = tiledlayout(num_rbss, num_plasmids*num_promoters, 'Padding','compact','TileSpacing','loose');

for idx = 1:nEC
    i = entries(idx).i;
    j = entries(idx).j;
    k = entries(idx).k;
    E = Exp_Data_Tensor{i,j,k};
    tile_num = j + num_promoters*(i-1) + num_promoters*num_plasmids*(k-1);
    ax = nexttile(tile_num);
    hold(ax,'on');

    Color_TU = entries(idx).color;
    num_instances = length(E.Data.Stats_Particles.List_instances);
    for qinst = 1:num_instances
        no_wells = length(E.Data.Stats_Particles.List_instances{qinst}.Index_Time_Particlesmax_wells);
        for r = 1:no_wells
            t_mumax_well = E.Data.Stats_Mu.List_instances{qinst}.Indices_Times_Mumax_wells(r);
            t_particlesmax_well = E.Data.Stats_Particles.List_instances{qinst}.Index_Time_Particlesmax_wells(r);
            if isempty(t_mumax_well) || isempty(t_particlesmax_well) || t_particlesmax_well <= t_mumax_well
                continue;
            end
            y = E.Data.Stats_Pi_p.List_instances{qinst}.Data_raw(t_mumax_well:t_particlesmax_well,r);
            x = E.Data.Stats_Mu.List_instances{qinst}.Data_raw(t_mumax_well:t_particlesmax_well,r);
            plot(ax,x,y,'Color',[color_grey 0.35],'LineStyle','-','LineWidth',0.55,'HandleVisibility','off');
        end
    end

    t_mumax_global = E.Data.Stats_Mu.Global_index_Time_Mumax_mean;
    t_particlesmax_global = E.Data.Stats_Particles.Global_index_Time_Particlesmax_mean;
    y_g = E.Data.Stats_Pi_p.Global_data_mean(t_mumax_global:t_particlesmax_global);
    x_g = E.Data.Stats_Mu.Global_data_mean(t_mumax_global:t_particlesmax_global);
    y_g_std = E.Data.Stats_Pi_p.Global_data_std(t_mumax_global:t_particlesmax_global);

    x = x_g(end:-1:1);
    y = y_g(end:-1:1); %#ok<NASGU>
    y_std = y_g_std(end:-1:1);
    yl = max(y_g(end:-1:1) - y_std, 1e-8);
    yu = y_g(end:-1:1) + y_std;
    x_coords = [x(:); flipud(x(:))];
    y_coords = [yl(:); flipud(yu(:))];
    fill(ax,x_coords,y_coords,Color_TU,'FaceAlpha',0.32,'EdgeColor','none','HandleVisibility','off');
    plot(ax,x_g,y_g,'Color',Color_TU,'LineWidth',2.2,'HandleVisibility','on');

    grid(ax,'on');
    set_axis_common(ax,12);
    ax.Title.FontSize = 12.5;
    title(ax,entries(idx).label,'Interpreter','none','FontWeight','bold');
    if (i==1) && (j==1)
        ylabel(ax,'$\Pi_\mathrm{p}$','Interpreter','latex','FontSize',15);
    end
    if k==num_rbss
        xlabel(ax,'$\mu$','Interpreter','latex','FontSize',15);
    end
    if ~isempty(x_g)
        xmin_mu = 0.005;
        xmax_mu = max(0.006,x_g(1));
        % Keep the final tick at the informative EC-specific mu_max, but
        % leave a small right margin so the label is not clipped in export.
        xpad_mu = max(0.00025, 0.045*(xmax_mu - xmin_mu));
        ax.XLim = [xmin_mu, xmax_mu + xpad_mu];
        force_mu_ticks(ax, xmin_mu, xmax_mu);
    end
    ylo = max(0.8*min(yl),1e-4);
    yhi = 1.2*max(yu);
    if isfinite(ylo) && isfinite(yhi) && yhi > ylo
        ax.YLim = [ylo yhi];
        force_y_ticks(ax, ylo, yhi);
    end
end

save_figure_if_requested(fig4,opt.OutputDir,[opt.FigurePrefix '_S2_Pi_vs_mu_tiles'],opt.SaveFigures);

% -------------------------------------------------------------------------
% Optional individual plots
% -------------------------------------------------------------------------
if individual_plots == 1
    make_individual_plots(Exp_Data_Tensor, entries, opt, color_grey);
end

end % function

% =========================================================================
% Helper plotting functions
% =========================================================================
function plot_ordered_pi_mu(ax, X, Pi, PiStd, Mu, MuStd, C, color_blue, bar_edge, font_size, show_xlabel)
    axes(ax); %#ok<LAXES>
    colororder(ax,[color_blue; 0 0 0]);
    yyaxis(ax,'left');
    b = bar(ax,X,Pi,'FaceColor','flat','EdgeColor',bar_edge,'LineWidth',0.5);
    b.CData = C;
    hold(ax,'on');
    errorbar(ax,X,Pi,PiStd,'CapSize',8,'LineWidth',1.3,'LineStyle','none','Color',color_blue);
    set(ax,'YScale','log');
    ylabel(ax,'$\Pi_\mathrm{p}(\mu_\mathrm{m})$','Interpreter','latex','FontSize',font_size+3);
    yyaxis(ax,'right');
    scatter(ax,X,Mu,42,'k','filled','MarkerFaceAlpha',0.85);
    errorbar(ax,X,Mu,MuStd,'CapSize',4,'LineWidth',1.0,'LineStyle','none','Color','k');
    ylabel(ax,'$\mu_\mathrm{m}\; (\mathrm{min}^{-1})$','Interpreter','latex','FontSize',font_size+3);
    if show_xlabel
        xlabel(ax,'Expression construct','FontSize',font_size,'Interpreter','none');
    end
    set_axis_common(ax,font_size);
    grid(ax,'on');
end

function plot_ordered_pi_mu_numeric(ax, x, Pi, PiStd, Mu, MuStd, C, color_blue, bar_edge, font_size, show_xlabel)
    axes(ax); %#ok<LAXES>
    colororder(ax,[color_blue; 0 0 0]);
    yyaxis(ax,'left');
    b = bar(ax,x,Pi,'FaceColor','flat','EdgeColor',bar_edge,'LineWidth',0.4);
    b.CData = C;
    hold(ax,'on');
    errorbar(ax,x,Pi,PiStd,'CapSize',4,'LineWidth',1.0,'LineStyle','none','Color',color_blue);
    set(ax,'YScale','log');
    ylabel(ax,'$\Pi_\mathrm{p}(\mu_\mathrm{m})$','Interpreter','latex','FontSize',font_size);
    yyaxis(ax,'right');
    scatter(ax,x,Mu,24,'k','filled','MarkerFaceAlpha',0.85);
    errorbar(ax,x,Mu,MuStd,'CapSize',3,'LineWidth',0.8,'LineStyle','none','Color','k');
    ylabel(ax,'$\mu_\mathrm{m}\; (\mathrm{min}^{-1})$','Interpreter','latex','FontSize',font_size);
    ax.XLim = [0.25, numel(x)+0.75];
    ax.XTick = [];
    ax.XTickLabel = {};
    if show_xlabel
        xlabel(ax,'','FontSize',font_size);
    end
    set_axis_common(ax,font_size);
    grid(ax,'on');
end

function plot_ordered_bar(ax, X, Y, YStd, C, color_blue, bar_edge, font_size, ylab, use_log)
    b = bar(ax,X,Y,'FaceColor','flat','EdgeColor',bar_edge,'LineWidth',0.5);
    b.CData = C;
    hold(ax,'on');
    errorbar(ax,X,Y,YStd,'CapSize',8,'LineWidth',1.3,'LineStyle','none','Color',color_blue);
    if use_log
        set(ax,'YScale','log');
    end
    ylabel(ax,ylab,'Interpreter','latex','FontSize',font_size+3);
    set_axis_common(ax,font_size);
    grid(ax,'on');
end

function plot_ordered_bar_numeric(ax, x, Y, YStd, C, color_blue, bar_edge, font_size, ylab, use_log)
    b = bar(ax,x,Y,'FaceColor','flat','EdgeColor',bar_edge,'LineWidth',0.4);
    b.CData = C;
    hold(ax,'on');
    errorbar(ax,x,Y,YStd,'CapSize',4,'LineWidth',1.0,'LineStyle','none','Color',color_blue);
    if use_log
        set(ax,'YScale','log');
    end
    ylabel(ax,ylab,'Interpreter','latex','FontSize',font_size);
    ax.XLim = [0.25, numel(x)+0.75];
    ax.XTick = [];
    ax.XTickLabel = {};
    set_axis_common(ax,font_size);
    grid(ax,'on');
end



function set_axis_common(ax,font_size)
    ax.FontName = 'Arial';
    ax.FontSize = font_size;
    ax.LineWidth = 0.8;
    ax.TickDir = 'out';
    ax.Box = 'on';
    ax.GridAlpha = 0.18;
    ax.MinorGridAlpha = 0.08;
    ax.XMinorGrid = 'on';
    ax.YMinorGrid = 'on';
    ax.TickLabelInterpreter = 'none';
end


function force_mu_ticks(ax, xmin_mu, xmax_mu)
    % Optimized x-axis tick labels for the 35-panel Pi-vs-mu figure.
    %
    % Design goals:
    %   - show exactly three ticks per tile;
    %   - keep the first and last ticks close to the plotted mu range;
    %   - make the middle tick a visually "nice" value, avoiding awkward
    %     labels such as 0.013 whenever a cleaner alternative is available;
    %   - keep a uniform slanted style across all panels.

    if nargin < 2 || isempty(xmin_mu)
        xmin_mu = ax.XLim(1);
    end
    if nargin < 3 || isempty(xmax_mu)
        xmax_mu = ax.XLim(2);
    end
    if ~all(isfinite([xmin_mu xmax_mu])) || xmax_mu <= xmin_mu
        return;
    end

    % Endpoints: round outward to 0.001 min^-1.  This keeps the final tick
    % informative for each EC-specific mu_max while avoiding too many digits.
    tick_unit = 0.001;
    xmin_tick = floor(xmin_mu/tick_unit) * tick_unit;
    xmax_tick = ceil(xmax_mu/tick_unit) * tick_unit;
    xmin_tick = max(0, xmin_tick);

    if xmax_tick <= xmin_tick
        xmax_tick = xmin_tick + tick_unit;
    end

    % Middle tick: prefer multiples of 0.005 for wider ranges, otherwise
    % multiples of 0.002.  This gives readable labels such as 0.010, 0.015,
    % 0.020, but still works for narrow ranges such as 0.005--0.011.
    span = xmax_tick - xmin_tick;
    if span >= 0.014
        mid_unit = 0.005;
    else
        mid_unit = 0.002;
    end

    mid_target = 0.5*(xmin_tick + xmax_tick);
    mid_tick = round(mid_target/mid_unit) * mid_unit;

    % If the preferred mid tick lands too close to an endpoint, fall back to
    % the exact midpoint rounded to 0.001.  This avoids labels collapsing
    % visually near the minimum or maximum tick.
    min_sep = 0.22 * span;
    if (mid_tick <= xmin_tick + min_sep) || (mid_tick >= xmax_tick - min_sep)
        mid_tick = round(mid_target/tick_unit) * tick_unit;
    end

    % Final safety: keep the middle tick strictly inside the endpoints.
    mid_tick = min(max(mid_tick, xmin_tick + tick_unit), xmax_tick - tick_unit);

    xt = [xmin_tick, mid_tick, xmax_tick];
    xt = round(xt, 4);

    ax.XTick = xt;
    ax.XTickLabel = arrayfun(@(v) sprintf('%.3f', v), xt, 'UniformOutput', false);
    ax.XTickMode = 'manual';
    ax.XTickLabelMode = 'manual';

    % Keep the exported PNG/SVG from clipping the rounded final tick.
    ax.XLim = [xmin_tick, xmax_tick + max(0.00025, 0.04*span)];

    % Uniform slant in every tile.
    ax.XTickLabelRotation = 35;
end


function force_y_ticks(ax, ymin_data, ymax_data)
    % Optimized y-axis tick labels for the 35-panel Pi-vs-mu figure.
    %
    % Design goals:
    %   - show exactly three ticks per tile;
    %   - keep the first and last ticks close to the plotted Pi range;
    %   - use rounded, publication-friendly values;
    %   - avoid overcrowding and inconsistent automatic tick density.

    if nargin < 2 || isempty(ymin_data)
        ymin_data = ax.YLim(1);
    end
    if nargin < 3 || isempty(ymax_data)
        ymax_data = ax.YLim(2);
    end
    if ~all(isfinite([ymin_data ymax_data])) || ymax_data <= ymin_data
        return;
    end

    span_data = ymax_data - ymin_data;
    step = nice_tick_step(span_data/2);

    ymin_tick = floor(ymin_data/step) * step;
    ymax_tick = ceil(ymax_data/step) * step;

    % If the lower limit is close to zero, use zero as the clean baseline.
    if ymin_data < 0.12*ymax_data
        ymin_tick = 0;
    end

    if ymax_tick <= ymin_tick
        ymax_tick = ymin_tick + 2*step;
    end

    % Choose a clean middle tick. Prefer the arithmetic midpoint of the
    % rounded endpoints, rounded to the same step.
    mid_target = 0.5*(ymin_tick + ymax_tick);
    mid_tick = round(mid_target/step) * step;

    % Safety: keep the middle tick strictly between endpoints.
    if mid_tick <= ymin_tick || mid_tick >= ymax_tick
        mid_tick = ymin_tick + 0.5*(ymax_tick - ymin_tick);
    end

    yt = [ymin_tick, mid_tick, ymax_tick];
    ax.YTick = yt;
    ax.YTickMode = 'manual';
    ax.YTickLabelMode = 'manual';
    ax.YTickLabel = arrayfun(@format_y_tick_label, yt, 'UniformOutput', false);

    % Add a little vertical room so endpoint labels and curves are not
    % clipped during PNG/SVG export.
    pad = max(0.02*(ymax_tick-ymin_tick), eps);
    ax.YLim = [max(0, ymin_tick), ymax_tick + pad];
end

function step = nice_tick_step(raw_step)
    % Return a readable step of the form 1, 2, 5, or 10 times a power of 10.
    if ~isfinite(raw_step) || raw_step <= 0
        step = 1;
        return;
    end
    exponent = floor(log10(raw_step));
    fraction = raw_step / 10^exponent;
    if fraction <= 1
        nice_fraction = 1;
    elseif fraction <= 2
        nice_fraction = 2;
    elseif fraction <= 5
        nice_fraction = 5;
    else
        nice_fraction = 10;
    end
    step = nice_fraction * 10^exponent;
end

function txt = format_y_tick_label(v)
    if abs(v) >= 100
        txt = sprintf('%.0f', v);
    elseif abs(v) >= 10
        txt = sprintf('%.0f', v);
    elseif abs(v) >= 1
        txt = sprintf('%.1f', v);
        txt = regexprep(txt,'\.0$','');
    else
        txt = sprintf('%.2g', v);
    end
end

function label = make_ec_label(E, i, j, k, q, label_mode)
    label_mode = lower(char(label_mode));
    if strcmp(label_mode,'none')
        label = sprintf('%02d',q);
        return;
    end
    if strcmp(label_mode,'bioparts')
        label = char(string(E.TU_Bioparts));
        return;
    end

    % Use Table S1-style primary EC codes.  First try the final manuscript
    % mapping inferred from the actual biopart names.  This is more robust
    % than relying on tensor indices for the L5 extension because the tensor
    % order used locally may not be identical to the table order.
    if isfield(E,'TU_Bioparts') && ~isempty(E.TU_Bioparts)
        label = table_s1_primary_code_from_bioparts(char(string(E.TU_Bioparts)));
        if ~startsWith(label,'EC')
            return;
        end
    end

    % Fallback: infer from tensor indices.
    label = table_s1_primary_code(i, j, k, q);

    % Last-resort fallback to explicit fields, but avoid overwriting valid
    % Table S1 labels.  This is mainly for older datasets not matching Lib35.
    if startsWith(label,'EC')
        candidate_fields = {'EC_code','EC_ID','Construct_code','Construct_ID','TU_code','TU_ID','ID','Name'};
        for n = 1:numel(candidate_fields)
            f = candidate_fields{n};
            if isfield(E,f) && ~isempty(E.(f))
                label = char(string(E.(f)));
                break;
            end
        end
    end
end

function label = table_s1_primary_code_from_bioparts(txt)
    % Table S1 mapping from biopart composition to manuscript EC codes.
    % Expected content examples include strings such as:
    %   pSC101,J23106,B0030
    %   pGreen,J23100,J61101
    % The parser is intentionally tolerant to BBa_ prefixes and separators.

    t = char(string(txt));
    t = strrep(t,'BBa_','');
    t = strrep(t,' ', '');
    t = strrep(t,';', ',');
    t = strrep(t,'-', ',');
    t = strrep(t,'_', '');
    tl = lower(t);

    if contains(tl,'ps101') || contains(tl,'psc101')
        plasmid = 1;
    elseif contains(tl,'pgreen')
        plasmid = 2;
    else
        label = 'EC_unknown';
        return;
    end

    if contains(t,'J23106')
        promoter = 1;
    elseif contains(t,'J23102')
        promoter = 2;
    elseif contains(t,'J23101')
        promoter = 3;
    elseif contains(t,'J23100')
        promoter = 4;
    else
        label = 'EC_unknown';
        return;
    end

    if contains(t,'B0030')
        rbs = 1;
    elseif contains(t,'B0032')
        rbs = 2;
    elseif contains(t,'J61100')
        rbs = 3;
    elseif contains(t,'J61101')
        rbs = 4;
    elseif contains(t,'B0034')
        rbs = 5;
    else
        label = 'EC_unknown';
        return;
    end

    % L5: pGreen + J23100, ordered exactly as Table S1.
    if plasmid == 2 && promoter == 4
        switch rbs
            case 1
                label = 'L5_1';   % B0030
            case 2
                label = 'L5_2';   % B0032
            case 5
                label = 'L5_3';   % B0034
            case 3
                label = 'L5_4';   % J61100
            case 4
                label = 'L5_5';   % J61101
        end
        return;
    end

    % L30 base library: 2 plasmids x 3 promoters x 4 RBSs.
    if promoter >= 1 && promoter <= 3 && rbs >= 1 && rbs <= 4
        n = (plasmid-1)*12 + (promoter-1)*4 + rbs;
        label = sprintf('L30_%02d', n);
        return;
    end

    % L6 extension within L30: B0034 in both backbones and first 3 promoters.
    if promoter >= 1 && promoter <= 3 && rbs == 5
        if plasmid == 1
            n = 24 + promoter;
        else
            n = 27 + promoter;
        end
        label = sprintf('L30_%02d', n);
        return;
    end

    label = 'EC_unknown';
end

function label = table_s1_primary_code(i, j, k, q)
    % Assumed tensor order used in SynTwin library data:
    % plasmids: 1=pSC101, 2=pGreen
    % promoters: 1=J23106, 2=J23102, 3=J23101, 4=J23100
    % RBSs: 1=B0030, 2=B0032, 3=J61100, 4=J61101, 5=B0034

    label = sprintf('EC%02d', q);

    % L5 extension: promoter J23100 only in pGreen, with five RBSs.
    % Check this first so it cannot be swallowed by any generic fallback.
    if i == 2 && j == 4
        switch k
            case 1
                label = 'L5_1';   % B0030
            case 2
                label = 'L5_2';   % B0032
            case 5
                label = 'L5_3';   % B0034
            case 3
                label = 'L5_4';   % J61100
            case 4
                label = 'L5_5';   % J61101
        end
        return;
    end

    % L24/L30 base library: 2 plasmids x 3 promoters x 4 RBSs.
    if j >= 1 && j <= 3 && k >= 1 && k <= 4 && i >= 1 && i <= 2
        n = (i-1)*12 + (j-1)*4 + k;
        label = sprintf('L30_%02d', n);
        return;
    end

    % L6 extension within L30: B0034 in both backbones and first 3 promoters.
    if j >= 1 && j <= 3 && k == 5 && i >= 1 && i <= 2
        if i == 1
            n = 24 + j;       % L30_25--L30_27, L6_01--L6_03
        else
            n = 27 + j;       % L30_28--L30_30, L6_04--L6_06
        end
        label = sprintf('L30_%02d', n);
        return;
    end
end

function save_figure_if_requested(fig,outdir,basename,do_save)
    set(fig,'Color','w');
    try, set(fig,'Renderer','painters'); catch, end
    drawnow;
    pause(5.0);
    if ~do_save
        return;
    end
    if ~exist(outdir,'dir')
        mkdir(outdir);
    end
    pngfile = fullfile(outdir,[basename '.png']);
    svgfile = fullfile(outdir,[basename '.svg']);
    try
        exportgraphics(fig,pngfile,'Resolution',600);
    catch
        print(fig,pngfile,'-dpng','-r600');
    end
    drawnow;
    pause(5.0);
    try
        exportgraphics(fig,svgfile,'ContentType','vector');
    catch
        print(fig,svgfile,'-dsvg');
    end
    drawnow;
end

function rgb = hex2rgb_local(hex)
    if isnumeric(hex)
        rgb = hex;
        return;
    end
    hex = char(hex);
    if hex(1) == '#'
        hex = hex(2:end);
    end
    rgb = reshape(sscanf(hex,'%2x')/255,1,3);
end

function make_individual_plots(Exp_Data_Tensor, entries, opt, color_grey)
    for idx = 1:numel(entries)
        i = entries(idx).i;
        j = entries(idx).j;
        k = entries(idx).k;
        E = Exp_Data_Tensor{i,j,k};
        fig = figure('Name',['Individual ' entries(idx).label],'Color','w', ...
            'Units','centimeters','Position',[1 1 16 12]);
        ax = axes(fig);
        hold(ax,'on');
        Color_TU = entries(idx).color;
        num_instances = length(E.Data.Stats_Particles.List_instances);
        for qinst = 1:num_instances
            no_wells = length(E.Data.Stats_Particles.List_instances{qinst}.Index_Time_Particlesmax_wells);
            for r = 1:no_wells
                t_mumax_well = E.Data.Stats_Mu.List_instances{qinst}.Indices_Times_Mumax_wells(r);
                t_particlesmax_well = E.Data.Stats_Particles.List_instances{qinst}.Index_Time_Particlesmax_wells(r);
                if isempty(t_mumax_well) || isempty(t_particlesmax_well) || t_particlesmax_well <= t_mumax_well
                    continue;
                end
                y = E.Data.Stats_Pi_p.List_instances{qinst}.Data_raw(t_mumax_well:t_particlesmax_well,r);
                x = E.Data.Stats_Mu.List_instances{qinst}.Data_raw(t_mumax_well:t_particlesmax_well,r);
                plot(ax,x,y,'Color',[color_grey 0.35],'LineStyle','-','LineWidth',0.6,'HandleVisibility','off');
            end
        end
        t_mumax_global = E.Data.Stats_Mu.Global_index_Time_Mumax_mean;
        t_particlesmax_global = E.Data.Stats_Particles.Global_index_Time_Particlesmax_mean;
        y_g = E.Data.Stats_Pi_p.Global_data_mean(t_mumax_global:t_particlesmax_global);
        x_g = E.Data.Stats_Mu.Global_data_mean(t_mumax_global:t_particlesmax_global);
        y_g_std = E.Data.Stats_Pi_p.Global_data_std(t_mumax_global:t_particlesmax_global);
        x = x_g(end:-1:1);
        yl = max(y_g(end:-1:1) - y_g_std(end:-1:1), 1e-8);
        yu = y_g(end:-1:1) + y_g_std(end:-1:1);
        fill(ax,[x(:); flipud(x(:))],[yl(:); flipud(yu(:))],Color_TU,'FaceAlpha',0.30,'EdgeColor','none');
        plot(ax,x_g,y_g,'Color',Color_TU,'LineWidth',2.5);
        set_axis_common(ax,opt.SupplementFontSize);
        xlabel(ax,'$\mu\; (\mathrm{min}^{-1})$','Interpreter','latex','FontSize',opt.SupplementFontSize+1);
        ylabel(ax,'$\Pi_\mathrm{p}\; (\mathrm{MEFL}\cdot\mathrm{Particle}^{-1}\cdot\mathrm{min}^{-1})$', ...
            'Interpreter','latex','FontSize',opt.SupplementFontSize+1);
        title(ax,entries(idx).label,'Interpreter','none','FontWeight','bold');
        grid(ax,'on');
        save_figure_if_requested(fig,opt.OutputDir,[opt.FigurePrefix '_individual_' entries(idx).label],opt.SaveFigures);
    end
end
