%% Show_Robustness_dma_Lib6_ALL_reduced_model
% Analyze robustness of the inferred B0034 parameter to fixed d_mA values.
%
% Required files are generated by
% Generate_Results_Lib6_ALL_reduced_model_set_dma.m.
%
% Outputs:
%   Figures/
%   Tables/

clear; clc;

ROOT = init_SynTwin(); %#ok<NASGU>
SCRIPT_DIR = fileparts(mfilename('fullpath'));
addpath(SCRIPT_DIR);

FIGURES_DIR = fullfile(SCRIPT_DIR,'Figures');
TABLES_DIR = fullfile(SCRIPT_DIR,'Tables');
if ~exist(FIGURES_DIR,'dir'), mkdir(FIGURES_DIR); end
if ~exist(TABLES_DIR,'dir'), mkdir(TABLES_DIR); end

Use_mean = 'Wells';
dma_values = [0.15,0.17,0.20,0.22,0.25]';
dm_ref = 0.20;
ndma = numel(dma_values);

theta_by_case = cell(ndma,1);
J_by_case = cell(ndma,1);
runs_per_case = zeros(ndma,1);

for case_idx = 1:ndma
    dm_tag = extractAfter(num2str(dma_values(case_idx)), '.');
    file_name = "Results_Tensor_Lib6_ALL_reduced_model_" + ...
        Use_mean + "_dma_" + dm_tag + ".mat";
    S = load(fullfile(SCRIPT_DIR,file_name));

    if ~isfield(S,'Estimated_parameters')
        error('Show_Robustness_dma_Lib6_ALL_reduced_model:MissingVariable', ...
            'Expected Estimated_parameters in %s.', file_name);
    end

    theta_i = S.Estimated_parameters.ALL_raw;
    theta_by_case{case_idx} = theta_i(:);
    J_by_case{case_idx} = S.Estimated_parameters.J_raw(:);
    runs_per_case(case_idx) = numel(theta_by_case{case_idx});
end

theta_median = cellfun(@median,theta_by_case);
theta_q25 = cellfun(@(x)prctile(x,25),theta_by_case);
theta_q75 = cellfun(@(x)prctile(x,75),theta_by_case);
J_median = cellfun(@median,J_by_case);
J_q25 = cellfun(@(x)prctile(x,25),J_by_case);
J_q75 = cellfun(@(x)prctile(x,75),J_by_case);

[~,i_ref] = min(abs(dma_values-dm_ref));
theta_ref = theta_median(i_ref);
J_ref = J_median(i_ref);

J_rel_median = 100*(J_median-J_ref)/J_ref;
J_rel_q25 = zeros(ndma,1);
J_rel_q75 = zeros(ndma,1);
for case_idx = 1:ndma
    rel_i = 100*(J_by_case{case_idx}-J_ref)/J_ref;
    J_rel_q25(case_idx) = prctile(rel_i,25);
    J_rel_q75(case_idx) = prctile(rel_i,75);
end

p = polyfit(log(dma_values),log(theta_median),1);
theta_sensitivity = p(1);
theta_fit = polyval(p,log(dma_values));
ss_res = sum((log(theta_median)-theta_fit).^2);
ss_tot = sum((log(theta_median)-mean(log(theta_median))).^2);
theta_R2 = 1-ss_res/ss_tot;

cost_summary = table(dma_values,runs_per_case,J_median,J_q25,J_q75, ...
    J_rel_median,J_rel_q25,J_rel_q75, ...
    'VariableNames',{'dmA','Nruns','J_median','J_q25','J_q75', ...
    'DeltaJ_median_percent','DeltaJ_q25_percent','DeltaJ_q75_percent'});

parameter_summary = table(dma_values,runs_per_case,theta_median,theta_q25,theta_q75, ...
    'VariableNames',{'dmA','Nruns','B0034_median','B0034_q25','B0034_q75'});

sensitivity_summary = table(theta_sensitivity,theta_R2, ...
    'VariableNames',{'LogLogSensitivity','R2'});

writetable(cost_summary,fullfile(TABLES_DIR,'Table_Lib6_dmA_cost_summary.csv'));
writetable(parameter_summary,fullfile(TABLES_DIR,'Table_Lib6_dmA_B0034_summary.csv'));
writetable(sensitivity_summary,fullfile(TABLES_DIR,'Table_Lib6_dmA_loglog_sensitivity.csv'));

cmap = parula(ndma);
fig1 = figure('Units','centimeters','Position',[2 2 30 12],'Color','w');
tiledlayout(1,2,'TileSpacing','compact','Padding','compact');

nexttile; hold on;
for case_idx = 1:ndma
    plot([dma_values(case_idx) dma_values(case_idx)], ...
        [J_rel_q25(case_idx) J_rel_q75(case_idx)],'k-','LineWidth',1.8);
    plot(dma_values(case_idx),J_rel_median(case_idx),'o', ...
        'MarkerFaceColor',cmap(case_idx,:),'MarkerEdgeColor','k','MarkerSize',7);
end
plot(dma_values,J_rel_median,'k-','LineWidth',1);
yline(0,'k--');
xlabel('$d_{mA}$','Interpreter','latex');
ylabel('relative cost change (%)');
title('Lib6 cost relative to $d_{mA}=0.20$','Interpreter','latex');
grid on; box on;

nexttile; hold on;
for case_idx = 1:ndma
    simple_violin(theta_by_case{case_idx},case_idx,cmap(case_idx,:),0.33,true,0.16);
end
plot([1 ndma],[theta_ref theta_ref],'r--','LineWidth',1.2);
xticks(1:ndma);
xticklabels(compose('%.2f',dma_values));
xlabel('$d_{mA}$','Interpreter','latex');
ylabel('B0034 $\kappa^0$ estimate','Interpreter','latex');
title(sprintf('Log-log sensitivity: %.3f',theta_sensitivity));
grid on; box on;

export_figure(fig1,fullfile(FIGURES_DIR,'Fig_Lib6_dmA_CostAndB0034'));

rng(1,'twister');
target_runs = min(runs_per_case);
collapsed = [];
for case_idx = 1:ndma
    x = theta_by_case{case_idx};
    if numel(x) > target_runs
        x = x(randperm(numel(x),target_runs));
    end
    collapsed = [collapsed; x(:)]; %#ok<AGROW>
end

fig2 = figure('Units','centimeters','Position',[2 2 14 12],'Color','w');
hold on;
simple_violin(collapsed,1,[0.75 0.85 0.95],0.34,true,0.10);
simple_violin(theta_by_case{i_ref},1,[0.20 0.45 0.75],0.18,true,0.18);
plot(1,theta_ref,'kd','MarkerFaceColor','k');
set(gca,'YScale','log');
xlim([0.5 1.5]); xticks(1); xticklabels({'B0034'});
ylabel('$\kappa^0$ estimate','Interpreter','latex');
title('Balanced collapsed distribution and reference');
grid on; box on;
export_figure(fig2,fullfile(FIGURES_DIR,'Fig_Lib6_dmA_Collapsed_B0034'));

fprintf('\n=== Lib6 dmA robustness summary ===\n');
fprintf('Reference dmA = %.3f\n',dm_ref);
fprintf('Balanced analysis uses %d runs per dmA.\n',target_runs);
disp(cost_summary);
disp(parameter_summary);
disp(sensitivity_summary);

function simple_violin(data,xpos,faceColor,halfWidth,showMedian,pointAlpha)
data = data(:); data = data(isfinite(data));
if isempty(data), return; end
n = numel(data);
if n == 1 || max(data)==min(data)
    plot(xpos,data,'o','Color',faceColor,'MarkerFaceColor',faceColor);
    return;
end
[f,yi] = ksdensity(data,'NumPoints',200);
f = f/max(f)*halfWidth;
patch([xpos+f fliplr(xpos-f)],[yi fliplr(yi)],faceColor, ...
    'FaceAlpha',0.45,'EdgeColor',faceColor);
jitter = (rand(n,1)-0.5)*halfWidth*0.5;
scatter(xpos+jitter,data,8,'MarkerFaceColor',faceColor, ...
    'MarkerEdgeColor','none','MarkerFaceAlpha',pointAlpha);
q = prctile(data,[25 50 75]);
plot([xpos xpos],[q(1) q(3)],'k-');
if showMedian
    plot([xpos-halfWidth*0.28 xpos+halfWidth*0.28],[q(2) q(2)],'k-','LineWidth',1.5);
end
end

function export_figure(fig_handle,file_base)
drawnow;
exportgraphics(fig_handle,[file_base '.png'],'Resolution',300);
exportgraphics(fig_handle,[file_base '.svg'],'ContentType','vector');
end
