%% Analyze_dmA_ratio_Lib30_ALL_TUs
% Analyze the turnover-to-resource ratio across all Lib30 constructs.
%
% Computes d_mA*(rho^0 + f_s(mu))/(kappa^0*varphi(mu)) for all 30 constructs
% and all five fixed d_mA values. Summaries are generated by construct, RBS,
% and reference-regime classification.
%
% Outputs:
%   Analysis_results/  MAT and CSV summaries.
%   Figures/           PNG and SVG plots.
%
% Usage:
%   Analyze_dmA_ratio_Lib30_ALL_TUs
%
% See README.md for the complete workflow.

clear; clc;

%% =========================
% User options
% ==========================
rho0 = 0.02;
Use_mean = 'Wells';
set_dma = [0.15, 0.17, 0.20, 0.22, 0.25];
dm_ref = 0.20;

SCRIPT_DIR = fileparts(mfilename('fullpath'));
RESULTS_DIR = SCRIPT_DIR;
ANALYSIS_DIR = fullfile(SCRIPT_DIR,'Analysis_results');
FIGURES_DIR = fullfile(SCRIPT_DIR,'Figures');
if ~exist(ANALYSIS_DIR,'dir'), mkdir(ANALYSIS_DIR); end
if ~exist(FIGURES_DIR,'dir'), mkdir(FIGURES_DIR); end

% Article-consistent colors
color_blue = hex2rgb('#00008B');
color_grey = hex2rgb('#4b4b4b'); %#ok<NASGU>
color_grey_boira = hex2rgb('#F2F2F2'); %#ok<NASGU>
color_grey_neutre = hex2rgb('#CCCCCC'); %#ok<NASGU>
RBS_colors_hex = {'#A8DADC','#F4A261','#B5E48C','#CDB4DB','#FFE066'}; % B0030, B0032, J61100, J61101, B0034
Promoter_colors_hex = {'#264653','#E76F51','#2A9D8F'}; % J23106, J23102, J23101

% Plot options
lineWidthCurve = 1.7;
lineWidthRef = 2.2;
lineWidthExp = 0.9;
markerSizeExp = 35;
baseFont = 12;
titleFont = 11;
figColor = 'w';
gridAlpha = 0.16;

dma_values = set_dma(:);
ndma = numel(dma_values);
[~, i_ref] = min(abs(dma_values - dm_ref));
cmap_dma = parula(ndma);

%% =========================
% Load all Lib30 results
% ==========================
ResultsByDmA = cell(ndma,1);
for i = 1:ndma
    dmA_tag = extractAfter(num2str(dma_values(i)), '.');
    if isempty(dmA_tag)
        dmA_tag = '0';
    end

    file_lib30 = fullfile(RESULTS_DIR, ...
        "Results_Tensor_Lib30_ALL_reduced_model_" + Use_mean + "_dma_" + dmA_tag + ".mat");

    if ~isfile(file_lib30)
        error('Lib30 results file not found: %s', file_lib30);
    end

    S = load(file_lib30);
    if ~isfield(S, 'Results_Tensor_Lib30_ALL_reduced')
        error('Variable Results_Tensor_Lib30_ALL_reduced not found in %s', file_lib30);
    end
    ResultsByDmA{i} = S.Results_Tensor_Lib30_ALL_reduced;
end

%% =========================
% Analyze across all dmA
% ==========================
Lib30 = analyze_library_tensor_all_dma(ResultsByDmA, dma_values, rho0, i_ref, ...
    color_blue, RBS_colors_hex, Promoter_colors_hex);

%% =========================
% Build global output structure
% ==========================
RatioAnalysis = struct();
RatioAnalysis.meta.dma_values = dma_values;
RatioAnalysis.meta.rho0 = rho0;
RatioAnalysis.meta.dm_ref = dm_ref;
RatioAnalysis.meta.i_ref = i_ref;
RatioAnalysis.meta.Use_mean = Use_mean;
RatioAnalysis.Lib30 = Lib30;

%% =========================
% Export summary tables
% ==========================
T_TU = build_summary_table(Lib30);
T_RBS = build_rbs_summary_table(Lib30);
T_regime = build_regime_summary_table(Lib30);

csv_tu = fullfile(ANALYSIS_DIR, 'RatioSummary_Lib30_byTU_all_dmA.csv');
csv_rbs = fullfile(ANALYSIS_DIR, 'RatioSummary_Lib30_byRBS_all_dmA.csv');
csv_regime = fullfile(ANALYSIS_DIR, 'RatioSummary_Lib30_byRegime_all_dmA.csv');

writetable(T_TU, csv_tu);
writetable(T_RBS, csv_rbs);
writetable(T_regime, csv_regime);

%% =========================
% Save MAT structure
% ==========================
mat_out = fullfile(ANALYSIS_DIR, 'RatioAnalysis_Lib30_all_dmA.mat');
save(mat_out, 'RatioAnalysis', '-mat');

%% =========================
% Figures
% ==========================
fig_tu = plot_tu_panels_all_dma(Lib30, dma_values, i_ref, cmap_dma, baseFont, titleFont, ...
    lineWidthCurve, lineWidthRef, lineWidthExp, markerSizeExp, figColor, gridAlpha);
export_figure(fig_tu, fullfile(FIGURES_DIR, 'Fig_Ratio_Lib30_AllTUs_all_dmA'));

fig_rbs = plot_summary_by_rbs_all_dma(Lib30, dma_values, i_ref, cmap_dma, baseFont, titleFont, ...
    lineWidthCurve, lineWidthRef, lineWidthExp, markerSizeExp, figColor, gridAlpha);
export_figure(fig_rbs, fullfile(FIGURES_DIR, 'Fig_Ratio_Lib30_SummaryByRBS_all_dmA'));

fig_regime = plot_summary_by_regime_all_dma(Lib30, dma_values, i_ref, cmap_dma, baseFont, titleFont, ...
    lineWidthCurve, lineWidthRef, lineWidthExp, markerSizeExp, figColor, gridAlpha);
export_figure(fig_regime, fullfile(FIGURES_DIR, 'Fig_Ratio_Lib30_SummaryByRegime_all_dmA'));

fprintf('\nSaved:\n');
fprintf('  %s\n', mat_out);
fprintf('  %s\n', csv_tu);
fprintf('  %s\n', csv_rbs);
fprintf('  %s\n', csv_regime);

%% =========================
% Local functions
% ==========================
function Lib = analyze_library_tensor_all_dma(ResultsByDmA, dma_values, rho0, i_ref, color_blue, RBS_colors_hex, Promoter_colors_hex)

    Rref = ResultsByDmA{i_ref};
    sz = size(Rref);
    nd = ndims(Rref);

    entries = {};
    subs = {};
    for idx = 1:numel(Rref)
        if ~isempty(Rref{idx})
            entries{end+1} = Rref{idx}; %#ok<AGROW>
            s = cell(1, nd);
            [s{:}] = ind2sub(sz, idx);
            subs{end+1} = cell2mat(s); %#ok<AGROW>
        end
    end

    nTU = numel(entries);
    TU = repmat(struct(), nTU, 1);

    for t = 1:nTU
        Xref = entries{t};
        subidx = subs{t};

        TU(t).subindices = subidx;
        TU(t).TU_Name = get_optional_text_field(Xref, {'TU_Name'});
        TU(t).TU_Bioparts = get_optional_text_field(Xref, {'TU_Bioparts'});
        TU(t).TU_Ori = get_optional_text_field(Xref, {'TU_Ori'});
        TU(t).TU_Promoter = get_optional_text_field(Xref, {'TU_Promoter'});
        TU(t).TU_RBS = get_optional_text_field(Xref, {'TU_RBS'});
        TU(t).color = assign_tu_color(TU(t), color_blue, RBS_colors_hex, Promoter_colors_hex);

        TU(t).dmA_values = dma_values(:);
        TU(t).ratio_by_dmA = cell(numel(dma_values),1);
        TU(t).mu_grid_by_dmA = cell(numel(dma_values),1);
        TU(t).mu_exp_by_dmA = cell(numel(dma_values),1);
        TU(t).ratio_exp_by_dmA = cell(numel(dma_values),1);
        TU(t).kappa_mean_by_dmA = nan(numel(dma_values),1);
        TU(t).ratio_exp_median_by_dmA = nan(numel(dma_values),1);
        TU(t).ratio_exp_mean_by_dmA = nan(numel(dma_values),1);
        TU(t).ratio_exp_min_by_dmA = nan(numel(dma_values),1);
        TU(t).ratio_exp_max_by_dmA = nan(numel(dma_values),1);
        TU(t).fraction_exp_ratio_gt_1_by_dmA = nan(numel(dma_values),1);
        TU(t).regime_exp_by_dmA = strings(numel(dma_values),1);

        for i = 1:numel(dma_values)
            Ri = ResultsByDmA{i};
            Xi = Ri{subidx(1), subidx(2), subidx(3)};

            mu_grid = get_field_flexible(Xi.Synthesis_predictions, {'Mu_values','mu_values','mu'});
            fs_grid = get_field_flexible(Xi.Synthesis_predictions, {'fs_pred_values','f_pred_values','fs_values'});
            varphi_grid = get_field_flexible(Xi.Synthesis_predictions, {'varphi_pred_values','phi_pred_values','varphi_values'});

            mu_grid = mu_grid(:);
            fs_grid = fs_grid(:);
            varphi_grid = varphi_grid(:);

            kappa = get_kappa_mean(Xi);
            ratio_grid = dma_values(i) .* (fs_grid + rho0) ./ (kappa .* varphi_grid);

            mu_exp = get_field_flexible(Xi, {'Mu_mumax_pmax_global_mean'});
            mu_exp = mu_exp(:);
            ratio_exp = interp1(mu_grid, ratio_grid, mu_exp, 'linear', 'extrap');

            TU(t).mu_grid_by_dmA{i} = mu_grid;
            TU(t).ratio_by_dmA{i} = ratio_grid;
            TU(t).mu_exp_by_dmA{i} = mu_exp;
            TU(t).ratio_exp_by_dmA{i} = ratio_exp;
            TU(t).kappa_mean_by_dmA(i) = kappa;
            TU(t).ratio_exp_median_by_dmA(i) = median(ratio_exp);
            TU(t).ratio_exp_mean_by_dmA(i) = mean(ratio_exp);
            TU(t).ratio_exp_min_by_dmA(i) = min(ratio_exp);
            TU(t).ratio_exp_max_by_dmA(i) = max(ratio_exp);
            TU(t).fraction_exp_ratio_gt_1_by_dmA(i) = mean(ratio_exp > 1);

            if all(ratio_exp > 1)
                TU(t).regime_exp_by_dmA(i) = "turnover-dominated";
            elseif all(ratio_exp < 1)
                TU(t).regime_exp_by_dmA(i) = "resource-dominated";
            else
                TU(t).regime_exp_by_dmA(i) = "mixed";
            end
        end

        TU(t).ratio_exp_median_ref = TU(t).ratio_exp_median_by_dmA(i_ref);
        TU(t).ratio_exp_mean_ref = TU(t).ratio_exp_mean_by_dmA(i_ref);
        TU(t).regime_ref = TU(t).regime_exp_by_dmA(i_ref);

        % envelope across dmA on common mu domain of reference grid
        mu_ref = TU(t).mu_grid_by_dmA{i_ref};
        ratio_stack = nan(numel(mu_ref), numel(dma_values));
        for i = 1:numel(dma_values)
            ratio_stack(:,i) = interp1(TU(t).mu_grid_by_dmA{i}, TU(t).ratio_by_dmA{i}, mu_ref, 'linear', 'extrap');
        end
        TU(t).mu_grid_ref = mu_ref;
        TU(t).ratio_q25 = prctile(ratio_stack, 25, 2);
        TU(t).ratio_q75 = prctile(ratio_stack, 75, 2);
        TU(t).ratio_min = min(ratio_stack, [], 2);
        TU(t).ratio_max = max(ratio_stack, [], 2);
    end

    Lib = struct();
    Lib.name = 'Lib30';
    Lib.nTU = nTU;
    Lib.TU = TU;
    Lib.uniqueRBS = unique(string({TU.TU_RBS}));
    Lib.uniqueRegimesRef = ["turnover-dominated","mixed","resource-dominated"];
end

function c = assign_tu_color(TU, color_blue, RBS_colors_hex, Promoter_colors_hex)
    rbs = string(TU.TU_RBS);
    prom = string(TU.TU_Promoter);

    if rbs == "BBa_B0030" || rbs == "B0030"
        c = hex2rgb(RBS_colors_hex{1});
    elseif rbs == "BBa_B0032" || rbs == "B0032"
        c = hex2rgb(RBS_colors_hex{2});
    elseif rbs == "BBa_J61100" || rbs == "J61100"
        c = hex2rgb(RBS_colors_hex{3});
    elseif rbs == "BBa_J61101" || rbs == "J61101"
        c = hex2rgb(RBS_colors_hex{4});
    elseif rbs == "BBa_B0034" || rbs == "B0034"
        c = hex2rgb(RBS_colors_hex{5});
    elseif prom == "BBa_J23106" || prom == "J23106"
        c = hex2rgb(Promoter_colors_hex{1});
    elseif prom == "BBa_J23102" || prom == "J23102"
        c = hex2rgb(Promoter_colors_hex{2});
    elseif prom == "BBa_J23101" || prom == "J23101"
        c = hex2rgb(Promoter_colors_hex{3});
    else
        c = color_blue;
    end
end

function kappa = get_kappa_mean(X)
    candidates = {'RBS_k0_sigma0_mean','RBS_k0_mean','kappa_mean'};
    kappa = [];
    for i = 1:numel(candidates)
        if isfield(X, candidates{i})
            kappa = X.(candidates{i});
            break;
        end
    end
    if isempty(kappa)
        error('Could not find RBS mean parameter field.');
    end
    kappa = kappa(1);
end

function val = get_field_flexible(S, candidates)
    val = [];
    for i = 1:numel(candidates)
        if isfield(S, candidates{i})
            val = S.(candidates{i});
            return;
        end
    end
    error('Could not find any of these fields: %s', strjoin(candidates, ', '));
end

function txt = get_optional_text_field(S, candidates)
    txt = "";
    for i = 1:numel(candidates)
        if isfield(S, candidates{i})
            v = S.(candidates{i});
            if isstring(v)
                txt = v;
            elseif ischar(v)
                txt = string(v);
            elseif iscell(v)
                try
                    txt = string(strjoin(string(v), ', '));
                catch
                    txt = "";
                end
            else
                try
                    txt = string(v);
                catch
                    txt = "";
                end
            end
            if ~isempty(txt)
                txt = txt(1);
            end
            return;
        end
    end
end

function T = build_summary_table(Lib)
    nTU = Lib.nTU;

    TU_Name   = strings(nTU,1);
    Ori       = strings(nTU,1);
    Promoter  = strings(nTU,1);
    RBS       = strings(nTU,1);
    RegimeRef = strings(nTU,1);
    RatioRefMedian = nan(nTU,1);
    RatioRefMean = nan(nTU,1);
    RatioAcrossDmA_Min = nan(nTU,1);
    RatioAcrossDmA_Max = nan(nTU,1);
    SensitivityMedian = nan(nTU,1);

    for t = 1:nTU
        X = Lib.TU(t);
        TU_Name(t) = string(X.TU_Name);
        Ori(t) = string(X.TU_Ori);
        Promoter(t) = string(X.TU_Promoter);
        RBS(t) = string(X.TU_RBS);
        RegimeRef(t) = string(X.regime_ref);
        RatioRefMedian(t) = X.ratio_exp_median_ref;
        RatioRefMean(t) = X.ratio_exp_mean_ref;
        RatioAcrossDmA_Min(t) = min(X.ratio_exp_median_by_dmA);
        RatioAcrossDmA_Max(t) = max(X.ratio_exp_median_by_dmA);

        p = polyfit(log(X.dmA_values), log(X.ratio_exp_median_by_dmA), 1);
        SensitivityMedian(t) = p(1);
    end

    T = table(TU_Name, Ori, Promoter, RBS, RegimeRef, ...
        RatioRefMedian, RatioRefMean, RatioAcrossDmA_Min, RatioAcrossDmA_Max, SensitivityMedian);
end

function T = build_rbs_summary_table(Lib)
    rbs_list = Lib.uniqueRBS(:);
    n = numel(rbs_list);

    RBS = strings(n,1);
    nTU = zeros(n,1);
    RefMedian_mean = nan(n,1);
    RefMedian_std = nan(n,1);
    AcrossDmA_Min = nan(n,1);
    AcrossDmA_Max = nan(n,1);
    FracTurnover_ref = nan(n,1);
    FracMixed_ref = nan(n,1);
    FracResource_ref = nan(n,1);

    for i = 1:n
        mask = strcmp(string({Lib.TU.TU_RBS}), rbs_list(i));
        X = Lib.TU(mask);
        RBS(i) = rbs_list(i);
        nTU(i) = numel(X);
        RefMedian_mean(i) = mean([X.ratio_exp_median_ref]);
        RefMedian_std(i) = std([X.ratio_exp_median_ref]);
        AcrossDmA_Min(i) = min(arrayfun(@(s) min(s.ratio_exp_median_by_dmA), X));
        AcrossDmA_Max(i) = max(arrayfun(@(s) max(s.ratio_exp_median_by_dmA), X));

        regs = string({X.regime_ref});
        FracTurnover_ref(i) = mean(regs == "turnover-dominated");
        FracMixed_ref(i) = mean(regs == "mixed");
        FracResource_ref(i) = mean(regs == "resource-dominated");
    end

    T = table(RBS, nTU, RefMedian_mean, RefMedian_std, AcrossDmA_Min, AcrossDmA_Max, ...
        FracTurnover_ref, FracMixed_ref, FracResource_ref);
end

function T = build_regime_summary_table(Lib)
    reg_list = Lib.uniqueRegimesRef(:);
    n = numel(reg_list);

    Regime = strings(n,1);
    nTU = zeros(n,1);
    RefMedian_mean = nan(n,1);
    RefMedian_std = nan(n,1);

    for i = 1:n
        mask = strcmp(string({Lib.TU.regime_ref}), reg_list(i));
        X = Lib.TU(mask);
        Regime(i) = reg_list(i);
        nTU(i) = numel(X);
        if ~isempty(X)
            RefMedian_mean(i) = mean([X.ratio_exp_median_ref]);
            RefMedian_std(i) = std([X.ratio_exp_median_ref]);
        end
    end

    T = table(Regime, nTU, RefMedian_mean, RefMedian_std);
end

function fig = plot_tu_panels_all_dma(Lib, dma_values, i_ref, cmap_dma, baseFont, titleFont, lineWidthCurve, lineWidthRef, lineWidthExp, markerSizeExp, figColor, gridAlpha)
    nrows = 5; ncols = 6;
    fig = figure('Units','centimeters','Position',[2 2 36 28],'Color',figColor);
    tiledlayout(nrows, ncols, 'TileSpacing','compact','Padding','compact');

    for t = 1:Lib.nTU
        X = Lib.TU(t);
        nexttile; hold on;

        % envelope across dmA
        fill([X.mu_grid_ref; flipud(X.mu_grid_ref)], [X.ratio_q25; flipud(X.ratio_q75)], X.color, ...
            'FaceAlpha', 0.18, 'EdgeColor', 'none');
        plot(X.mu_grid_ref, X.ratio_min, ':', 'Color', 0.55*X.color + 0.45*[1 1 1], 'LineWidth', 0.9);
        plot(X.mu_grid_ref, X.ratio_max, ':', 'Color', 0.55*X.color + 0.45*[1 1 1], 'LineWidth', 0.9);

        for i = 1:numel(dma_values)
            lw = lineWidthCurve;
            if i == i_ref
                lw = lineWidthRef;
            end
            plot(X.mu_grid_by_dmA{i}, X.ratio_by_dmA{i}, '-', 'LineWidth', lw, 'Color', cmap_dma(i,:));
            scatter(X.mu_exp_by_dmA{i}, X.ratio_exp_by_dmA{i}, markerSizeExp, 'o', ...
                'MarkerFaceColor', cmap_dma(i,:), 'MarkerEdgeColor', 'k', 'LineWidth', 0.35);
        end
        yline(1, '--', 'Color', [0.2 0.2 0.2], 'LineWidth', lineWidthExp);

        mu_all = vertcat(X.mu_exp_by_dmA{:});
        if max(mu_all) > min(mu_all)
            xpad = 0.07 * (max(mu_all) - min(mu_all));
        else
            xpad = 0.001;
        end
        xlim([min(mu_all)-xpad, max(mu_all)+xpad]);

        title(compose_title(X), 'Interpreter', 'none', 'FontSize', titleFont);
        xlabel('\mu (min^{-1})');
        ylabel('ratio');
        grid on; box on;
        ax = gca;
        set(ax, 'FontSize', baseFont, 'LineWidth', 1.0, 'Layer', 'top');
        ax.GridAlpha = gridAlpha;
        ax.MinorGridAlpha = gridAlpha*0.9;
    end

    sgtitle('Lib30: ratio = d_{mA}(\rho^0 + f_s)/(\kappa\varphi) for all TUs across d_{mA}', ...
        'FontSize', titleFont+1, 'FontWeight', 'bold');
end

function fig = plot_summary_by_rbs_all_dma(Lib, dma_values, i_ref, cmap_dma, baseFont, titleFont, lineWidthCurve, lineWidthRef, lineWidthExp, markerSizeExp, figColor, gridAlpha)
    rbs_order = ["BBa_B0030","BBa_B0032","BBa_B0034","BBa_J61100","BBa_J61101"];
    alt_order = ["B0030","B0032","B0034","J61100","J61101"];

    fig = figure('Units','centimeters','Position',[2 2 62 16],'Color',figColor);
    tiledlayout(1,5,'TileSpacing','compact','Padding','compact');

    for iR = 1:5
        nexttile; hold on;
        mask = strcmp(string({Lib.TU.TU_RBS}), rbs_order(iR)) | strcmp(string({Lib.TU.TU_RBS}), alt_order(iR));
        X = Lib.TU(mask);

        if isempty(X)
            title(char(rbs_order(iR)), 'Interpreter','none', 'FontSize', titleFont);
            axis off;
            continue;
        end

        % Envelope and reference curve for each TU
        for k = 1:numel(X)
            fill([X(k).mu_grid_ref; flipud(X(k).mu_grid_ref)], ...
                 [X(k).ratio_q25; flipud(X(k).ratio_q75)], ...
                 X(k).color, 'FaceAlpha', 0.08, 'EdgeColor', 'none');

            plot(X(k).mu_grid_ref, X(k).ratio_by_dmA{i_ref}, '-', ...
                 'LineWidth', lineWidthRef, 'Color', X(k).color);
        end

        % New markers:
        %   square  -> ratio at median of experimental mu minima across TUs
        %   diamond -> ratio at median of experimental mu maxima across TUs
        mu_min_vals = nan(numel(X),1);
        mu_max_vals = nan(numel(X),1);
        ratio_at_mu_min = nan(numel(X),1);
        ratio_at_mu_max = nan(numel(X),1);

        for k = 1:numel(X)
            mu_exp_ref = X(k).mu_exp_by_dmA{i_ref};
            ratio_exp_ref = X(k).ratio_exp_by_dmA{i_ref};

            [mu_min_vals(k), idx_min] = min(mu_exp_ref);
            [mu_max_vals(k), idx_max] = max(mu_exp_ref);

            ratio_at_mu_min(k) = ratio_exp_ref(idx_min);
            ratio_at_mu_max(k) = ratio_exp_ref(idx_max);
        end

        mu_min_med = median(mu_min_vals);
        mu_max_med = median(mu_max_vals);
        ratio_min_med = median(ratio_at_mu_min);
        ratio_max_med = median(ratio_at_mu_max);

        % plot all individual TU min/max experimental points faintly
        scatter(mu_min_vals, ratio_at_mu_min, 0.65*markerSizeExp, 's', ...
            'MarkerFaceColor', [0.85 0.85 0.85], ...
            'MarkerEdgeColor', [0.35 0.35 0.35], ...
            'LineWidth', 0.35);

        scatter(mu_max_vals, ratio_at_mu_max, 0.65*markerSizeExp, 'd', ...
            'MarkerFaceColor', [0.65 0.65 0.65], ...
            'MarkerEdgeColor', [0.20 0.20 0.20], ...
            'LineWidth', 0.35);

        % plot median min/max markers prominently
        scatter(mu_min_med, ratio_min_med, 1.5*markerSizeExp, 's', ...
            'MarkerFaceColor', [1 1 1], ...
            'MarkerEdgeColor', [0 0 0], ...
            'LineWidth', 1.0);

        scatter(mu_max_med, ratio_max_med, 1.5*markerSizeExp, 'd', ...
            'MarkerFaceColor', [0 0 0], ...
            'MarkerEdgeColor', [0 0 0], ...
            'LineWidth', 1.0);

        yline(1, '--', 'Color', [0.2 0.2 0.2], 'LineWidth', lineWidthExp);
        title(char(rbs_order(iR)), 'Interpreter','none', 'FontSize', titleFont);
        xlabel('\mu (min^{-1})');
        ylabel('ratio');
        grid on; box on;
        ax = gca;
        set(ax, 'FontSize', baseFont, 'LineWidth', 1.0, 'Layer', 'top');
        ax.GridAlpha = gridAlpha;
        ax.MinorGridAlpha = gridAlpha*0.9;
    end

    % nexttile; hold on;
    % % summary of median ratio vs dmA by RBS
    % for iR = 1:5
    %     mask = strcmp(string({Lib.TU.TU_RBS}), rbs_order(iR)) | strcmp(string({Lib.TU.TU_RBS}), alt_order(iR));
    %     X = Lib.TU(mask);
    %     if isempty(X), continue; end
    % 
    %     med_stack = nan(numel(X), numel(dma_values));
    %     for kk = 1:numel(X)
    %         med_stack(kk,:) = X(kk).ratio_exp_median_by_dmA(:)';
    %     end
    % 
    %     y = mean(med_stack,1);
    %     yq25 = prctile(med_stack,25,1);
    %     yq75 = prctile(med_stack,75,1);
    %     col = X(1).color;
    % 
    %     xfill = [dma_values(:); flipud(dma_values(:))];
    %     yfill = [yq25(:); flipud(yq75(:))];
    %     if numel(xfill) == numel(yfill) && all(isfinite(yfill))
    %         fill(xfill, yfill, col, 'FaceAlpha', 0.12, 'EdgeColor', 'none');
    %     end
    % 
    %     plot(dma_values, y, '-', 'LineWidth', 1.8, 'Color', col);
    %     plot(dma_values(i_ref), y(i_ref), 'kd', 'MarkerFaceColor', 'w', 'MarkerSize', 4.5);
    % end
    % xlabel('d_{mA} (min^{-1})');
    % ylabel('mean TU median ratio');
    % title('Per-RBS summary across d_{mA}', 'FontSize', titleFont);
    % grid on; box on;
    % ax = gca;
    % set(ax, 'FontSize', baseFont, 'LineWidth', 1.0, 'Layer', 'top');
    % ax.GridAlpha = gridAlpha;
    % ax.MinorGridAlpha = gridAlpha*0.9;
    % 
    % sgtitle('Lib30: ratio summary grouped by RBS across d_{mA}', ...
    %     'FontSize', titleFont+1, 'FontWeight', 'bold');
end

    

function fig = plot_summary_by_regime_all_dma(Lib, dma_values, i_ref, cmap_dma, baseFont, titleFont, lineWidthCurve, lineWidthRef, lineWidthExp, markerSizeExp, figColor, gridAlpha)
    reg_order = ["turnover-dominated","mixed","resource-dominated"];
    fig = figure('Units','centimeters','Position',[2 2 30 16],'Color',figColor);
    tiledlayout(2,2,'TileSpacing','compact','Padding','compact');

    for iR = 1:3
        nexttile; hold on;
        mask = strcmp(string({Lib.TU.regime_ref}), reg_order(iR));
        X = Lib.TU(mask);

        for k = 1:numel(X)
            fill([X(k).mu_grid_ref; flipud(X(k).mu_grid_ref)], [X(k).ratio_q25; flipud(X(k).ratio_q75)], X(k).color, ...
                'FaceAlpha', 0.08, 'EdgeColor', 'none');
            plot(X(k).mu_grid_ref, X(k).ratio_by_dmA{i_ref}, '-', 'LineWidth', lineWidthRef, 'Color', X(k).color);
            scatter(median(X(k).mu_exp_by_dmA{i_ref}), X(k).ratio_exp_median_by_dmA(i_ref), 28, ...
                'MarkerFaceColor', X(k).color, 'MarkerEdgeColor', 'k', 'LineWidth', 0.35);
        end

        yline(1, '--', 'Color', [0.2 0.2 0.2], 'LineWidth', lineWidthExp);
        title(sprintf('%s (n=%d)', char(reg_order(iR)), numel(X)), 'Interpreter','none', 'FontSize', titleFont);
        xlabel('\mu (min^{-1})');
        ylabel('ratio');
        grid on; box on;
        ax = gca;
        set(ax, 'FontSize', baseFont, 'LineWidth', 1.0, 'Layer', 'top');
        ax.GridAlpha = gridAlpha;
        ax.MinorGridAlpha = gridAlpha*0.9;
    end

    nexttile; hold on;
    for iR = 1:3
        mask = strcmp(string({Lib.TU.regime_ref}), reg_order(iR));
        X = Lib.TU(mask);
        if isempty(X), continue; end

        med_stack = nan(numel(X), numel(dma_values));
        for kk = 1:numel(X)
            med_stack(kk,:) = X(kk).ratio_exp_median_by_dmA(:)';
        end
        y = mean(med_stack,1);
        yq25 = prctile(med_stack,25,1);
        yq75 = prctile(med_stack,75,1);

        if iR == 1
            col = [0.70 0.85 0.70];
        elseif iR == 2
            col = [0.95 0.85 0.55];
        else
            col = [0.80 0.80 0.90];
        end

        xfill = [dma_values(:); flipud(dma_values(:))];
        yfill = [yq25(:); flipud(yq75(:))];
        if numel(xfill) == numel(yfill) && all(isfinite(yfill))
            fill(xfill, yfill, col, ...
                'FaceAlpha', 0.18, 'EdgeColor', 'none');
        end;
        plot(dma_values, y, '-', 'LineWidth', 1.8, 'Color', col*0.75);
        plot(dma_values(i_ref), y(i_ref), 'kd', 'MarkerFaceColor', 'w', 'MarkerSize', 4.5);
    end
    xlabel('d_{mA} (min^{-1})');
    ylabel('mean TU median ratio');
    title('Per-regime summary across d_{mA}', 'FontSize', titleFont);
    grid on; box on;
    ax = gca;
    set(ax, 'FontSize', baseFont, 'LineWidth', 1.0, 'Layer', 'top');
    ax.GridAlpha = gridAlpha;
    ax.MinorGridAlpha = gridAlpha*0.9;

    sgtitle('Lib30: ratio summary grouped by regime across d_{mA}', ...
        'FontSize', titleFont+1, 'FontWeight', 'bold');
end

function txt = compose_title(X)
    name = string(X.TU_Name);
    if strlength(name) == 0
        parts = [string(X.TU_Ori), string(X.TU_Promoter), string(X.TU_RBS)];
        parts = parts(parts ~= "");
        txt = strjoin(parts, ' | ');
    else
        txt = name;
    end
end

function export_figure(fig_handle, file_base)
    set(fig_handle, 'PaperPositionMode', 'auto');
    drawnow;
    exportgraphics(fig_handle, [file_base '.png'], 'Resolution', 300);
    exportgraphics(fig_handle, [file_base '.svg'], 'ContentType', 'vector');
end

function c = hex2rgb(hex)
    hex = char(hex);
    hex = strrep(hex, '#', '');
    if numel(hex) ~= 6
        error('hex2rgb:InvalidInput', 'Expected a 6-character hex code.');
    end
    c = [hex2dec(hex(1:2)), hex2dec(hex(3:4)), hex2dec(hex(5:6))] / 255;
end
